name: MSurvivalKeys
version: 5.0
main: pl.msurvival.keys.MSurvivalKeys
api-version: '1.21'
author: Milekz

commands:
  keysmenu:
    description: Otwiera menu kluczy
    usage: /keysmenu
  menuitem:
    description: Daje item menu
    usage: /menuitem
  key:
    description: Używa klucza
    usage: /key use <typ>
  keyadmin:
    description: Administracja kluczami
    usage: /keyadmin <give|reset|reload|item> <gracz> [typ] [ilość]

permissions:
  msurvivalkeys.admin:
    description: Dostęp do administracji kluczami
    default: op
