name: MSurvivalKeys
version: 2.0
main: pl.msurvival.keys.MSurvivalKeys
api-version: '1.21'
author: Milekz

commands:
  keysmenu:
    usage: /keysmenu
  key:
    usage: /key use <typ>
  keyadmin:
    usage: /keyadmin <give|item|reset|reload> <gracz> [typ] [ilosc]

permissions:
  msurvivalkeys.admin:
    default: op
